-- 新增字段部门类型：dept_type。
-- 作用于区分当前部门的职能，值对应着字典 sys_dept_type
-- 例 分局 1 -> 派出所 11 -> 执法办案队 111 + 社区警务队 112 -> 社区辖区 1121 + 办案队 1111 
INSERT INTO `sys_dict_type` (`dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('部门类型', 'sys_dept_type', '0', 'admin', '2023-07-04 16:25:32', '', NULL, NULL);

INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (0, '公安分局', '1', 'sys_dept_type', NULL, 'default', 'N', '0', 'admin', '2023-07-04 16:25:58', '', NULL, NULL);
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1, '派出所', '101', 'sys_dept_type', NULL, 'default', 'N', '0', 'admin', '2023-07-04 16:26:14', 'admin', '2023-07-04 16:27:19', '1');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (10, '执法办案队', '10101', 'sys_dept_type', NULL, 'default', 'N', '0', 'admin', '2023-07-04 16:27:41', 'admin', '2023-07-04 16:30:50', '101');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (20, '社区警务队', '10102', 'sys_dept_type', NULL, 'default', 'N', '0', 'admin', '2023-07-04 16:27:58', 'admin', '2023-07-04 16:30:56', '101');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (30, '指挥调度室', '10103', 'sys_dept_type', NULL, 'default', 'N', '0', 'admin', '2023-07-04 16:28:39', 'admin', '2023-07-04 16:31:02', '101');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (40, '其他部门', '10104', 'sys_dept_type', NULL, 'default', 'N', '0', 'admin', '2023-07-04 16:29:08', 'admin', '2023-07-04 16:31:06', '101');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (11, '办案分组', '1010101', 'sys_dept_type', NULL, 'default', 'N', '0', 'admin', '2023-07-04 16:31:23', '', NULL, '10101');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (12, '其他部门', '1010100', 'sys_dept_type', NULL, 'default', 'N', '0', 'admin', '2023-07-04 16:31:50', '', NULL, '10101');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (22, '其他部门', '1010200', 'sys_dept_type', NULL, 'default', 'N', '0', 'admin', '2023-07-04 16:32:07', '', NULL, '10102');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (21, '社区', '1010201', 'sys_dept_type', NULL, 'default', 'N', '0', 'admin', '2023-07-04 16:32:20', '', NULL, '10102');

INSERT INTO `sq_database`.`sys_dict_type` (`dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('重点关注人员级别', 'important_level', '0', 'admin', '2023-07-10 15:02:06', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_type` (`dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('与房东关系', 'family_member_relationship', '0', 'admin', '2023-07-11 14:19:35', 'admin', '2023-07-11 14:27:35', NULL);


INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '祖父', '1', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:49:47', 'admin', '2023-07-11 14:41:54', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '祖母', '2', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:49:58', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 3, '外祖父', '3', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:50:09', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 4, '外祖母', '4', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:50:23', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 5, '姑丈', '5', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:50:46', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 6, '姑妈', '6', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:50:57', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 7, '伯父', '7', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:51:16', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 8, '伯母', '8', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:51:37', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 9, '叔父', '9', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:51:58', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 10, '婶婶', '10', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:52:22', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 11, '舅舅', '11', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:52:36', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 12, '舅妈', '12', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:52:46', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 13, '姨丈', '13', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:53:02', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 14, '姨妈', '14', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:53:25', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 0, '父亲', '15', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:53:40', 'admin', '2023-07-11 14:38:02', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 0, '母亲', '16', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:53:54', 'admin', '2023-07-11 14:38:09', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 17, '表哥', '17', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:54:18', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 18, '表弟', '18', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:54:35', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 19, '表姐', '19', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:54:49', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 20, '表妹', '20', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:55:08', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 21, '堂哥', '21', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:55:20', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 22, '堂弟', '22', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:55:42', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 23, '堂姐', '23', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:55:55', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 24, '堂妹', '24', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:56:05', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 0, '妻子', '25', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:56:25', 'admin', '2023-07-11 14:38:19', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 0, '丈夫', '26', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:56:39', 'admin', '2023-07-11 14:38:23', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '哥哥', '27', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:56:56', 'admin', '2023-07-11 14:40:12', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 28, '嫂子', '28', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:57:08', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '弟弟', '29', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:57:30', 'admin', '2023-07-11 14:40:21', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 30, '弟媳', '30', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:57:55', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '姐姐', '31', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:58:11', 'admin', '2023-07-11 14:39:59', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 32, '姐夫', '32', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:58:22', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '妹妹', '33', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:58:40', 'admin', '2023-07-11 14:39:54', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 34, '妹婿', '34', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:59:16', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 35, '侄女', '35', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 14:59:29', 'admin', '2021-06-15 15:00:01', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 36, '侄子', '36', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 15:00:16', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '儿子', '37', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 15:00:29', 'admin', '2023-07-11 14:41:37', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '儿媳', '38', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 15:00:57', 'admin', '2023-07-11 14:39:40', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '女儿', '39', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 15:01:13', 'admin', '2023-07-11 14:41:32', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '女婿', '40', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 15:01:28', 'admin', '2023-07-11 14:40:04', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 41, '外甥', '41', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 15:01:45', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 42, '外甥女', '42', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 15:01:59', '', NULL, NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 1, '孙子', '43', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 15:02:16', 'admin', '2023-07-11 14:40:17', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '孙女', '44', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 15:02:29', 'admin', '2023-07-11 14:41:43', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 2, '外孙', '45', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 15:02:45', 'admin', '2023-07-11 14:41:46', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 3, '外孙女', '46', 'family_member_relationship', NULL, NULL, 'N', '0', 'admin', '2021-06-15 15:03:02', 'admin', '2023-07-11 14:39:36', NULL);
INSERT INTO `sq_database`.`sys_dict_data` ( `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ( 0, '本人', '0', 'family_member_relationship', NULL, 'primary', 'N', '0', 'admin', '2023-07-11 14:40:48', 'admin', '2023-07-11 14:41:02', NULL);
