###################################################################
########          这里是 系统正式环境配置 的通用配置         ############
###################################################################

# #################################################################
spring:
    # Redis 配置
    redis:
        # 地址
        host: localhost
        # 端口，默认为6379
        port: 6379
        # 数据库索引
        database: 0
        # 密码
        password:
    # 数据源配置
    datasource:
        druid:
            master:
                # 主库数据源
                url: jdbc:mysql://192.168.100.3:3306/sq_database?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: XAjy@2020

# Swagger配置
swagger:
    # 是否开启swagger
    enabled: true
    # 请求前缀
    pathMapping: /dev-api

server:
    port: 8080