###################################################################
########          这里是 系统开发环境配置 的通用配置         ############
###################################################################

# #################################################################

spring:
    # Redis 配置
    redis:
        # 地址
        host: localhost
        # 端口，默认为6379
        port: 6379
        # 数据库索引
        database: 0
        # 密码
        password:
    # 数据源配置
    datasource:
        druid:
            master:
                # 主库数据源
<<<<<<< HEAD
                url: jdbc:mysql://localhost:3306/sq_database?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: admin
=======
                url: jdbc:mysql://localhost:3308/sq_database?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: root
>>>>>>> fc1e3ed2add3bb98c2a2514c47a486213c442590

# Swagger配置
swagger:
    # 是否开启swagger
    enabled: true
    # 请求前缀
    pathMapping: /dev-api

server:
<<<<<<< HEAD
    port: 8080
=======
    port: 8080
>>>>>>> fc1e3ed2add3bb98c2a2514c47a486213c442590
